sonar.projectKey=Warj-Group_API5BD2026Frontend
sonar.organization=warj-group
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Adicione estas linhas para evitar falsos positivos em arquivos de configuração
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# Exclusões focadas em Nuxt
sonar.exclusions=**/node_modules/**, **/.nuxt/**, **/.output/**, **/dist/**, **/coverage/**, .eslint.config.mjs, nuxt.config.ts