# Identificação Obrigatória
sonar.projectKey=Warj-Group_API5BD2026Fronted
sonar.organization=warj-group

# Configurações de Análise
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxExecutionTime=15

# Exclusões para acelerar a análise
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/coverage/**