#!/bin/sh
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ ! $BRANCH =~ ^(main|sprint-[0-9]+)$ && ! $BRANCH =~ ^(feature|hotfix|release)\/WARJ-[0-9]+-.+$ ]]; then
  echo "❌ ERRO: Nome da branch fora do padrão Warj-Group!"
  echo "Padrões aceitos: main, sprint-X ou {feature|hotfix|release}/WARJ-X-Descricao"
  exit 1
fi