name: Frontend CI & SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - sprint-1
      - sprint-2
      - sprint-3
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]

    steps:
      - name: Checkout
        # v4.2.2 (Verificado)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9 # Garante a versão 9 do pnpm para compatibilidade com Node 22

      - name: Install node
        # v4.2.0 (Verificado)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

  sonarcloud:
    name: SonarCloud Scan
    needs: ci # O Sonar só roda se o Lint e Typecheck passarem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        # v4.2.1 (Verificado)
        uses: SonarSource/sonarqube-scan-action@724367c337b56d3575971a1792ca8a221f736024
        with:
          args: >
            -Dsonar.projectKey=Warj-Group_API5BD2026Fronted
            -Dsonar.organization=warj-group
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}